baseURL = "https://arlmedia.ca/"
languageCode = "en-us"
title = "ARLMedia"
theme = "basic"
[params]
author = "Andrew Lloyd"
description = "My portfolio site"
googleAnalytics = "UA-187046479"
gh_url = "https://api.github.com/users"
gh_user = "AndrewRLloyd88"
gh_query = "?sort=created&order=asc"
pygmentsUseClasses = true